version: '3.8'

services:
  # MySQL 数据库服务
  mysql:
    image: mysql:8.0
    container_name: rbac-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ApiServerDb
      MYSQL_USER: apiserver
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - rbac-network

  # Redis 缓存服务 (可选)
  redis:
    image: redis:7-alpine
    container_name: rbac-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5
    networks:
      - rbac-network

  # 后端 API 服务
  apiserver:
    build:
      context: ./src
      dockerfile: ApiServer.WebApi/Dockerfile
    container_name: rbac-api
    restart: unless-stopped
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=ApiServerDb;Uid=apiserver;Pwd=123456;
      - JwtSettings__SecretKey=YourSuperSecretKeyThatIsAtLeast32CharactersLong!
      - JwtSettings__Issuer=ApiServer
      - JwtSettings__Audience=ApiServerClient
      - JwtSettings__ExpiryMinutes=60
      - JwtSettings__RefreshTokenExpiryDays=7
      - Redis__ConnectionString=redis:6379
      - Serilog__MinimumLevel=Information
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - rbac-network

  # 前端 Web 服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rbac-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000/api
    depends_on:
      - apiserver
    networks:
      - rbac-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  rbac-network:
    driver: bridge